#
# Set to true, if you want debug messages to be send.
# Debug messages start with a [DEBUG]. This may cause spam to your console.
#
Debug: false
NPC:
  #
  # Set the colors used for the different states of the players a NPC is associated with.
  # The state "AFK" is only used, if EssentialsX is installed.
  #
  # You can use the following colors:
  #   AQUA
  #   BLACK
  #   BLUE
  #   DARK_AQUA
  #   DARK_BLUE
  #   DARK_GRAY
  #   DARK_GREEN
  #   DARK_PURPLE
  #   DARK_RED
  #   GOLD
  #   GRAY
  #   GREEN
  #   LIGHT_PURPLE
  #   RED
  #   WHITE
  #   YELLOW
  #
  Colors:
    Online: 'GREEN'
    Offline: 'RED'
    AFK: 'GOLD'