name: StatusNPC
version: ${project.version}
author: Andre_601

main: com.andre601.statusnpc.StatusNPC

#
# The plugin *should* work in older versions.
# This is only to prevent the "Plugin xyz doesn't define an api-version" spam on startup.
#
api-version: '1.13'

#
# We use softdepend over depend as this would cause stacktraces to be thrown in the console (Not pretty!)
# In our case do we require Citizens, but Essentials (EssentialsX) is optional.
#
softdepend:
- Citizens
- Essentials