name: StatusNPC
version: ${project.version}
author: Andre_601

main: com.andre601.statusnpc.StatusNPC

api-version: '1.13'

softdepend:
- Citizens
- Essentials

commands:
  statusnpc:
    usage: <command> [help|set <player> <id>|remove <player>]
    description: Sets an NPC as a StatusNPC to display the current status of a player.
    aliases: [snpc]
    permission: statusnpc.use

permissions: 
  statusnpc.use:
    description: Permission to access the /statusnpc commands.
    default: op